code --install-extension antfu.goto-alias
code --install-extension antfu.iconify
code --install-extension antfu.unocss
code --install-extension antiantisepticeye.vscode-color-picker
code --install-extension ctcuff.font-preview
code --install-extension dbaeumer.vscode-eslint
code --install-extension docker.docker
code --install-extension donjayamanne.githistory
code --install-extension dotjoshjohnson.xml
code --install-extension github.vscode-github-actions
code --install-extension humao.rest-client
code --install-extension ionutvmi.reg
code --install-extension jock.svg
code --install-extension kennylong.kubernetes-yaml-formatter
code --install-extension lokalise.i18n-ally
code --install-extension mark-wiemer.vscode-autohotkey-plus-plus
code --install-extension mhutchie.git-graph
code --install-extension ms-playwright.playwright
code --install-extension ms-python.debugpy
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-python.vscode-python-envs
code --install-extension ms-vscode.cmake-tools
code --install-extension ms-vscode.powershell
code --install-extension seunlanlege.action-buttons
code --install-extension stylelint.vscode-stylelint
code --install-extension vue.volar
code --install-extension wayou.vscode-todo-highlight
code --install-extension yechunan.json-color-token
